#####################
#   Список команд   #
#####################

#commandtype:
#    1: talk
#    2: action
#    3: skill

commands:
    north:
        type: action
        alias:
        - north
        - север
    south:
        type: action
        alias:
        - south
        - юг
    west:
        type: action
        alias:
        - west
        - запад
    east:
        type: action
        alias:
        - east
        - восток
    look:
        type: action
        alias:
        - look
        - смотреть
        - взглянуть

