#####################
#   Список команд   #
#####################

commands:
    # Перемещение
    north:
        type: action
        alias:
        - north
        - север
    south:
        type: action
        alias:
        - south
        - юг
    west:
        type: action
        alias:
        - west
        - запад
    east:
        type: action
        alias:
        - east
        - восток
    up:
        type: action
        alias:
        - up
        - вверх
        - наверх
    down:
        type: action
        alias:
        - down
        - вниз
        - низ

    # Осмотр окружающей местности
    look:
        type: action
        alias:
        - look
        - смотреть
        - взглянуть

    # Список игроков онлайн
    who:
        type: action
        alias:
        - who
        - кто
        - онлайн

    # Выход из игры
    quit:
        type: system
        alias:
        - quit
        - конец

    # Импорт зон и рас из файлов
    import:
        type: system
        alias:
        - import
        - импорт

    # Чат
    chat:
        type: action
        alias:
        - chat
        - ooc
        - чат
        - болтать
        - ооц
    say:
        type: action
        alias:
        - say
        - сказать
        - произнести
    shout:
        type: action
        alias:
        - shout
        - yell
        - кричать
        - крикнуть
        - орать

    # открыть
    open:
        type: action
        alias:
        - open
        - открыть
